travis:
  secure:
    BINSTAR_TOKEN: juI3pAt8r1jPAWPbt0vuQ0k9OJWXwgU7XfehIWcbkeFRU17nAe+Yw5s0E7ZerSi5gcoAy2hkkTHE25OPPe0muXOrLJ15qhWhc7f2Q2MxbPrVRVwXdphnVnlEQ5Qz48Cb4885bawMv8NNQf0i6SnyHHCj6UisfpTa/Au26yXMwP8VhR0tNRfC3CWn1mggZ82HmPHhafoQVnzfAdK7L5JZlZL7TQ8ryrfh/41Ki3fJi/myM/CoZ8VrnAt9Khr/omx4rv86Uz1XKfjScV7nimiei7xNfPTUnqEqxEIRMcmnzGSyUNruXqD+6YLAS0Y8PA391LNk28EpoTUl8HGUiJItWImo5Y+y1zqAfdJBBNyYocJKk0yL8bx2LqivQbzvW5qaxubsVLK+B3G9ANYb2ccxKhTEzyGiN7N4KwN4+DbpCJiPdBTH+yslNwhFupVdvZxn+iQ+4mSahlPJd3LlQ4eEaJsXqfuP5x9PEti6yH6knZtyBYsf9ckjpLf9nUbZw2KO25jBEIqjF03WVhDKFGVCiq6j7bEkKCCDjxn+5oaJ+y7aDTrfH0q4JkoYLN9XRfKnIWZRy4lyYSoRpTpl2GAvycdI0D7dO+CMLUnXZs6meBA7mZP4iqy7aXVHFry7C8mVQfbvzLi8XkkKqBSnFm9XurZzUXbvFZbW/2owyLrCPV0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
